### ISSUE TITLE
Front-end para registro de producción

### ISSUE THREAD

**Issue by lizfloresg** [ecotierraperu/issue#319]
#### Descripción ####
Front-end para registrar producción
#### Consideraciones ####
Colocar en pestaña como entrega de producción.
#### Tasks ####
- [x] Mockups.
- [x] Diseño de Index.
- [x] Implementación de Index.
- [x] Registrar Producción.
 - [x] Diseño de formulario
 - [x] Implementación de formulario
    - [x] Agregar variedad.
    - [x] Editar variedad.
    - [x] Eliminar variedad.
    - [x] Guardar producción.
- [x] Editar Producción.
- [x] Eliminar Producción.
- [x] Permisos de Producción.
- [x] Limpiar código.
- [x] Testeo final.
