### ISSUE TITLE
Front-end para registrar formas de entrega

### ISSUE THREAD

**Issue by lizfloresg** [ecotierraperu/issue#323]
#### Descripción ####
Front-end para registrar formas de entrega y su unidad de medida.
#### Tasks ####
- [x] Mockups.
- [x] Diseño de Index
 - [x] Formas de Entrega
 - [x] Etapas de producción
- [x] Implementación de Index
 - [x] Formas de entrega.
 - [x] Etapas de producción.
- [x] Registrar
 - [x] Registrar forma de entrega.
 - [x] Registrar actividad
 - [x] Remover cultivo(controladores)
- [x] Editar forma de entrega.
- [x] Eliminar actividad
- [x] Eliminar forma de entrega.
- [x] Permisos para forma de entrega.
