### ISSUE TITLE
Front-end de registro de etapas de producción

### ISSUE THREAD

**Issue by lizfloresg** [ecotierraperu/issue#338]
#### Descripción ####
Front-end de registro de etapas de producción
#### Tasks ####
- [x] Mockups.
 - [x] Index de etapas de producción.
 - [x] Registrar/Editar etapa de producción.
- [x] Listar etapas.
- [x] Registrar etapa.
- [x] Editar etapa.
 - [x] Movimiento de etapas
- [x] Eliminar etapa.
- [x] **Permisos para etapas.**
 - [x] Ver etapas de producción (lateral-nav).
 - [x] Agregar actividad.
 - [x] Agregar etapa de producción.
 - [x] Editar etapa de producción.
 - [x] Movimiento de etapa de producción.
 - [x] Eliminar etapa de producción.
