### ISSUE TITLE
Front-end para esquemas de cooperativa

### ISSUE THREAD

**Issue by lizfloresg** [ecotierraperu/issue#352]
#### Descripción ####
Front-end para esquemas de cooperativa.
#### Tasks ####
- [x] Mockups.
- [x] Index de Esquemas
 - [x] Diseño de Index.
 - [x] Implementación de Index.
- [x] Registrar Esquemas.
 - [x] Diseño de formulario
 - [x] Implementación de formulario
    - [x] Agregar Especie de grupo
    - [x] Editar especie
    - [x] Eliminar especie
    - [x] Guardar esquema
- [x] Editar Esquema.
- [x] Imagen de Esquema
   - [x] Cargar imagen de Esquema.
   - [x] Ver imagen de Esquema.
   - [x] Reemplazar imagen de Esquema.
- [x] Eliminar Esquemas.
- [x] Permisos de Esquemas.
- [x] Limpiar código
- [x] Testeo final

**Comment by lizfloresg** [comment]
Posiblemente eliminar archivos de indicacion.html
