### ISSUE TITLE
Front-end para selección de esquema

### ISSUE THREAD

**Issue by lizfloresg** [ecotierraperu/issue#359]
#### Descripción ####
Front-end para asignar esquema a georreferencia
#### Tasks ####
- [x] Mockups
- [x] Index de Parcela
- [x] Perfil de Parcela
  - [x] Diseño
  - [x] Implementación
- [x] Registrar selección de esquema
  - [x] Diseño de formulario
  - [x] Implementación de formulario
- [x] Editar selección de esquema
- [x] Eliminar selección de esquema
- [x] Permisos de Selección de Esquema
  - [x] Permisos en perfil de georreferencia
  - [x] Permisos en reportes
- [x] Reporte de esquemas seleccionados. (Incluirlo en apartado de reportes)
- [x] Registrar selección de esquema en historial de georreferencia
- [x] Limpiar código
- [x] Testeo final
