### ISSUE TITLE
Galería de vivero

### ISSUE THREAD

**Issue by lizfloresg** [ecotierraperu/issue#368]
#### Descripción ####
Implementar la galería de fotografías para vivero.
#### Tasks ####
- [x] Galería de vivero
  - [x] **Mostrar fotos de álbum**
  - [x] agregar foto
  - [x] Mostrar foto
  - [x] Eliminar foto
  - [x] Borrar fotos 
- [x] Galería de periodo
  - [x] agregar foto
  - [x] Mostrar foto
  - [x] Eliminar foto
  - [x] Borrar fotos
