### ISSUE TITLE
Permisos de usuario

### ISSUE THREAD

**Issue by lizfloresg** [ecotierraperu/issue#402]
#### Descripción ####
Permisos de front-end y back-end para la gestión de cooperativas.

#### Tasks ####
- [x] Sesión de usuarios en backend.
- [x] Sesión de usuarios en frontend.
- [x] Modificar Error de Tool para mensajes por código.
- [x] Verificar envío de notificación para desarrolladores cuando se produzca un error.
- [x] Permisos de botones en frontend
     - [x] Verificar permisos de gestión de usuarios. (Invitar, ver usuarios, ver detalle de invitado, reenviar invitación, borrar invitado)
- [x] Selección de cooperativa.
